// ============================================================
// data.js - Dữ liệu từ vựng và bài tập HSK1 / HSK2 / HSK3
// ============================================================

const HSK_DATA = {
  hsk1: {
    name: "HSK 1",
    level: 1,
    color: "#27ae60",
    gradient: "linear-gradient(135deg, #1a6b3c, #27ae60)",
    description: "150 từ vựng cơ bản",
    vocabulary: [
      { hanzi: "你好", pinyin: "nǐ hǎo", meaning: "xin chào", example: "你好！你叫什么名字？", ex_vi: "Xin chào! Bạn tên là gì?", category: "Chào hỏi" },
      { hanzi: "谢谢", pinyin: "xiè xie", meaning: "cảm ơn", example: "谢谢你的帮助！", ex_vi: "Cảm ơn bạn đã giúp đỡ!", category: "Chào hỏi" },
      { hanzi: "再见", pinyin: "zài jiàn", meaning: "tạm biệt", example: "明天见，再见！", ex_vi: "Hẹn gặp lại ngày mai, tạm biệt!", category: "Chào hỏi" },
      { hanzi: "对不起", pinyin: "duì bu qǐ", meaning: "xin lỗi", example: "对不起，我迟到了。", ex_vi: "Xin lỗi, tôi đến muộn.", category: "Chào hỏi" },
      { hanzi: "不客气", pinyin: "bú kè qi", meaning: "không có gì", example: "不客气，这是我应该做的。", ex_vi: "Không có gì, đây là điều tôi nên làm.", category: "Chào hỏi" },
      { hanzi: "我", pinyin: "wǒ", meaning: "tôi", example: "我是学生。", ex_vi: "Tôi là học sinh.", category: "Đại từ" },
      { hanzi: "你", pinyin: "nǐ", meaning: "bạn / anh / chị", example: "你好吗？", ex_vi: "Bạn có khỏe không?", category: "Đại từ" },
      { hanzi: "他", pinyin: "tā", meaning: "anh ấy / ông ấy", example: "他是我的朋友。", ex_vi: "Anh ấy là bạn tôi.", category: "Đại từ" },
      { hanzi: "她", pinyin: "tā", meaning: "cô ấy / bà ấy", example: "她叫李梅。", ex_vi: "Cô ấy tên là Lý Mai.", category: "Đại từ" },
      { hanzi: "我们", pinyin: "wǒ men", meaning: "chúng tôi / chúng ta", example: "我们是朋友。", ex_vi: "Chúng ta là bạn bè.", category: "Đại từ" },
      { hanzi: "什么", pinyin: "shén me", meaning: "cái gì / gì", example: "这是什么？", ex_vi: "Đây là cái gì?", category: "Đại từ nghi vấn" },
      { hanzi: "哪", pinyin: "nǎ", meaning: "nào / đâu", example: "你是哪国人？", ex_vi: "Bạn là người nước nào?", category: "Đại từ nghi vấn" },
      { hanzi: "哪儿", pinyin: "nǎr", meaning: "ở đâu", example: "你在哪儿？", ex_vi: "Bạn đang ở đâu?", category: "Đại từ nghi vấn" },
      { hanzi: "多少", pinyin: "duō shao", meaning: "bao nhiêu (số lớn)", example: "这个多少钱？", ex_vi: "Cái này bao nhiêu tiền?", category: "Đại từ nghi vấn" },
      { hanzi: "几", pinyin: "jǐ", meaning: "mấy / bao nhiêu (số nhỏ)", example: "你有几个朋友？", ex_vi: "Bạn có mấy người bạn?", category: "Đại từ nghi vấn" },
      { hanzi: "是", pinyin: "shì", meaning: "là", example: "我是老师。", ex_vi: "Tôi là giáo viên.", category: "Động từ" },
      { hanzi: "有", pinyin: "yǒu", meaning: "có", example: "我有一本书。", ex_vi: "Tôi có một cuốn sách.", category: "Động từ" },
      { hanzi: "没有", pinyin: "méi yǒu", meaning: "không có", example: "我没有钱。", ex_vi: "Tôi không có tiền.", category: "Động từ" },
      { hanzi: "吃", pinyin: "chī", meaning: "ăn", example: "我想吃饺子。", ex_vi: "Tôi muốn ăn sủi cảo.", category: "Động từ" },
      { hanzi: "喝", pinyin: "hē", meaning: "uống", example: "你喝茶吗？", ex_vi: "Bạn uống trà không?", category: "Động từ" },
      { hanzi: "来", pinyin: "lái", meaning: "đến / đi đến", example: "请来我家。", ex_vi: "Hãy đến nhà tôi.", category: "Động từ" },
      { hanzi: "去", pinyin: "qù", meaning: "đi / đến (xa người nói)", example: "我去学校。", ex_vi: "Tôi đi đến trường.", category: "Động từ" },
      { hanzi: "看", pinyin: "kàn", meaning: "nhìn / xem", example: "我看书。", ex_vi: "Tôi đọc sách.", category: "Động từ" },
      { hanzi: "说", pinyin: "shuō", meaning: "nói", example: "他说汉语。", ex_vi: "Anh ấy nói tiếng Hán.", category: "Động từ" },
      { hanzi: "叫", pinyin: "jiào", meaning: "tên là / gọi", example: "我叫王明。", ex_vi: "Tôi tên là Vương Minh.", category: "Động từ" },
      { hanzi: "爱", pinyin: "ài", meaning: "yêu / yêu thích", example: "我爱你。", ex_vi: "Tôi yêu em.", category: "Động từ" },
      { hanzi: "好", pinyin: "hǎo", meaning: "tốt / tốt lành", example: "今天天气很好。", ex_vi: "Hôm nay thời tiết rất tốt.", category: "Tính từ" },
      { hanzi: "大", pinyin: "dà", meaning: "lớn / to", example: "这个苹果很大。", ex_vi: "Quả táo này rất to.", category: "Tính từ" },
      { hanzi: "小", pinyin: "xiǎo", meaning: "nhỏ / bé", example: "我有一只小猫。", ex_vi: "Tôi có một con mèo nhỏ.", category: "Tính từ" },
      { hanzi: "多", pinyin: "duō", meaning: "nhiều", example: "这里的人很多。", ex_vi: "Nơi đây có rất nhiều người.", category: "Tính từ" },
      { hanzi: "少", pinyin: "shǎo", meaning: "ít", example: "我的钱很少。", ex_vi: "Tiền của tôi rất ít.", category: "Tính từ" },
      { hanzi: "高兴", pinyin: "gāo xìng", meaning: "vui mừng / vui vẻ", example: "认识你很高兴！", ex_vi: "Rất vui được gặp bạn!", category: "Tính từ" },
      { hanzi: "很", pinyin: "hěn", meaning: "rất", example: "我很好。", ex_vi: "Tôi rất khỏe.", category: "Trạng từ" },
      { hanzi: "也", pinyin: "yě", meaning: "cũng", example: "我也是学生。", ex_vi: "Tôi cũng là học sinh.", category: "Trạng từ" },
      { hanzi: "都", pinyin: "dōu", meaning: "đều / tất cả", example: "他们都是中国人。", ex_vi: "Họ đều là người Trung Quốc.", category: "Trạng từ" },
      { hanzi: "不", pinyin: "bù", meaning: "không (phủ định)", example: "我不去。", ex_vi: "Tôi không đi.", category: "Trạng từ" },
      { hanzi: "今天", pinyin: "jīn tiān", meaning: "hôm nay", example: "今天是星期一。", ex_vi: "Hôm nay là thứ Hai.", category: "Thời gian" },
      { hanzi: "明天", pinyin: "míng tiān", meaning: "ngày mai", example: "明天我去北京。", ex_vi: "Ngày mai tôi đi Bắc Kinh.", category: "Thời gian" },
      { hanzi: "昨天", pinyin: "zuó tiān", meaning: "hôm qua", example: "昨天我去了医院。", ex_vi: "Hôm qua tôi đi bệnh viện.", category: "Thời gian" },
      { hanzi: "年", pinyin: "nián", meaning: "năm", example: "今年是2025年。", ex_vi: "Năm nay là năm 2025.", category: "Thời gian" },
      { hanzi: "月", pinyin: "yuè", meaning: "tháng", example: "这个月是一月。", ex_vi: "Tháng này là tháng Một.", category: "Thời gian" },
      { hanzi: "日", pinyin: "rì", meaning: "ngày", example: "今天是三月一日。", ex_vi: "Hôm nay là ngày 1 tháng 3.", category: "Thời gian" },
      { hanzi: "老师", pinyin: "lǎo shī", meaning: "giáo viên / thầy cô", example: "我的老师很好。", ex_vi: "Giáo viên của tôi rất tốt.", category: "Danh từ" },
      { hanzi: "学生", pinyin: "xué shēng", meaning: "học sinh / sinh viên", example: "他是大学生。", ex_vi: "Anh ấy là sinh viên đại học.", category: "Danh từ" },
      { hanzi: "朋友", pinyin: "péng yǒu", meaning: "bạn bè", example: "她是我的好朋友。", ex_vi: "Cô ấy là bạn thân của tôi.", category: "Danh từ" },
      { hanzi: "中国", pinyin: "Zhōng guó", meaning: "Trung Quốc", example: "他来自中国。", ex_vi: "Anh ấy đến từ Trung Quốc.", category: "Địa danh" },
      { hanzi: "北京", pinyin: "Běi jīng", meaning: "Bắc Kinh", example: "北京是中国的首都。", ex_vi: "Bắc Kinh là thủ đô của Trung Quốc.", category: "Địa danh" },
      { hanzi: "学校", pinyin: "xué xiào", meaning: "trường học", example: "我们学校很大。", ex_vi: "Trường chúng tôi rất lớn.", category: "Địa danh" },
      { hanzi: "一", pinyin: "yī", meaning: "một (số 1)", example: "一个苹果", ex_vi: "Một quả táo", category: "Số đếm" },
      { hanzi: "二", pinyin: "èr", meaning: "hai (số 2)", example: "两个人", ex_vi: "Hai người", category: "Số đếm" },
      { hanzi: "三", pinyin: "sān", meaning: "ba (số 3)", example: "三本书", ex_vi: "Ba cuốn sách", category: "Số đếm" },
      { hanzi: "四", pinyin: "sì", meaning: "bốn (số 4)", example: "四个学生", ex_vi: "Bốn học sinh", category: "Số đếm" },
      { hanzi: "五", pinyin: "wǔ", meaning: "năm (số 5)", example: "五块钱", ex_vi: "Năm đồng", category: "Số đếm" },
      { hanzi: "六", pinyin: "liù", meaning: "sáu (số 6)", example: "六个月", ex_vi: "Sáu tháng", category: "Số đếm" },
      { hanzi: "七", pinyin: "qī", meaning: "bảy (số 7)", example: "七天", ex_vi: "Bảy ngày", category: "Số đếm" },
      { hanzi: "八", pinyin: "bā", meaning: "tám (số 8)", example: "八点", ex_vi: "Tám giờ", category: "Số đếm" },
      { hanzi: "九", pinyin: "jiǔ", meaning: "chín (số 9)", example: "九月", ex_vi: "Tháng Chín", category: "Số đếm" },
      { hanzi: "十", pinyin: "shí", meaning: "mười (số 10)", example: "十年", ex_vi: "Mười năm", category: "Số đếm" },
    ],
    quiz: [
      { q: '"你好" có nghĩa là gì?', opts: ['Tạm biệt', 'Xin chào', 'Cảm ơn', 'Xin lỗi'], ans: 1 },
      { q: '"我" có nghĩa là gì?', opts: ['Bạn', 'Anh ấy', 'Tôi', 'Chúng ta'], ans: 2 },
      { q: '"吃" có nghĩa là gì?', opts: ['Uống', 'Nhìn', 'Ăn', 'Ngủ'], ans: 2 },
      { q: '"大" có nghĩa là gì?', opts: ['Nhỏ', 'Lớn', 'Nhiều', 'Ít'], ans: 1 },
      { q: 'Từ nào có nghĩa là "ngày mai"?', opts: ['今天', '昨天', '明天', '后天'], ans: 2 },
      { q: 'Từ nào có nghĩa là "giáo viên"?', opts: ['学生', '朋友', '医生', '老师'], ans: 3 },
      { q: '"谢谢" đọc như thế nào?', opts: ['nǐ hǎo', 'zài jiàn', 'xiè xie', 'duì bu qǐ'], ans: 2 },
      { q: '"很" có nghĩa là gì?', opts: ['Không', 'Đều', 'Cũng', 'Rất'], ans: 3 },
      { q: 'Chữ nào có nghĩa là "uống"?', opts: ['吃', '来', '喝', '去'], ans: 2 },
      { q: '"我们" có nghĩa là gì?', opts: ['Tôi', 'Bạn', 'Họ', 'Chúng tôi'], ans: 3 },
      { q: '"北京" là tên của?', opts: ['Thành phố Thượng Hải', 'Thủ đô Trung Quốc', 'Nước Trung Quốc', 'Tỉnh Quảng Đông'], ans: 1 },
      { q: '"不" có nghĩa là gì?', opts: ['Rất', 'Cũng', 'Không', 'Đều'], ans: 2 },
      { q: 'Pinyin của "六" là?', opts: ['qī', 'bā', 'wǔ', 'liù'], ans: 3 },
      { q: '"学校" có nghĩa là gì?', opts: ['Bệnh viện', 'Trường học', 'Cửa hàng', 'Nhà hàng'], ans: 1 },
      { q: '"说" có nghĩa là gì?', opts: ['Đọc', 'Nghe', 'Nói', 'Xem'], ans: 2 },
      { q: 'Chữ nào có nghĩa là "hôm nay"?', opts: ['明天', '昨天', '今天', '后天'], ans: 2 },
      { q: '"都" có nghĩa là gì?', opts: ['Cũng', 'Rất', 'Không', 'Đều / tất cả'], ans: 3 },
      { q: '"高兴" có nghĩa là gì?', opts: ['Buồn', 'Tức giận', 'Vui mừng', 'Lo lắng'], ans: 2 },
      { q: '"是" trong câu "我是老师" có nghĩa là gì?', opts: ['Có', 'Là', 'Muốn', 'Biết'], ans: 1 },
      { q: 'Pinyin của "朋友" là?', opts: ['lǎo shī', 'xué shēng', 'péng yǒu', 'yī shēng'], ans: 2 },
    ],
    fillBlank: [
      { sentence: "你___吗？(khỏe)", blank: "好", hint: "hǎo", context: "Bạn có ___ không?" },
      { sentence: "我___老师。(là)", blank: "是", hint: "shì", context: "Tôi ___ giáo viên." },
      { sentence: "___！你叫什么名字？(xin chào)", blank: "你好", hint: "nǐ hǎo", context: "___! Bạn tên là gì?" },
      { sentence: "她___我的朋友。(là)", blank: "是", hint: "shì", context: "Cô ấy ___ bạn tôi." },
      { sentence: "我很___。(vui mừng)", blank: "高兴", hint: "gāo xìng", context: "Tôi rất ___." },
      { sentence: "今天___！(thời tiết tốt → 天气好)", blank: "天气好", hint: "tiān qì hǎo", context: "Hôm nay ___!" },
      { sentence: "我___去学校。(đi, dạng phủ định)", blank: "不", hint: "bù", context: "Tôi ___ đi trường." },
      { sentence: "他们___是学生。(đều)", blank: "都", hint: "dōu", context: "Họ ___ là học sinh." },
      { sentence: "你___哪儿？(đi)", blank: "去", hint: "qù", context: "Bạn ___ đâu?" },
      { sentence: "谢___！(cảm ơn)", blank: "谢", hint: "xiè", context: "Cảm ơn!" },
    ],
    listening: [
      { text: "你好", meaning: "Xin chào", opts: ['Xin chào', 'Cảm ơn', 'Tạm biệt', 'Xin lỗi'], ans: 0 },
      { text: "谢谢", meaning: "Cảm ơn", opts: ['Tạm biệt', 'Cảm ơn', 'Xin lỗi', 'Xin chào'], ans: 1 },
      { text: "再见", meaning: "Tạm biệt", opts: ['Xin chào', 'Cảm ơn', 'Tạm biệt', 'Không có gì'], ans: 2 },
      { text: "我是老师", meaning: "Tôi là giáo viên", opts: ['Tôi là học sinh', 'Tôi là bác sĩ', 'Tôi là giáo viên', 'Tôi là bạn'], ans: 2 },
      { text: "今天天气很好", meaning: "Hôm nay thời tiết rất tốt", opts: ['Hôm nay rất vui', 'Hôm nay thời tiết rất tốt', 'Hôm qua thời tiết rất tốt', 'Ngày mai thời tiết rất tốt'], ans: 1 },
      { text: "我有很多朋友", meaning: "Tôi có rất nhiều bạn bè", opts: ['Tôi có nhiều sách', 'Bạn tôi rất tốt', 'Tôi có rất nhiều bạn bè', 'Chúng tôi là bạn'], ans: 2 },
      { text: "你去哪儿", meaning: "Bạn đi đâu?", opts: ['Bạn đến từ đâu?', 'Bạn đi đâu?', 'Bạn ở đâu?', 'Bạn làm gì?'], ans: 1 },
      { text: "我不吃肉", meaning: "Tôi không ăn thịt", opts: ['Tôi không uống nước', 'Tôi ăn rất nhiều', 'Tôi không ăn thịt', 'Tôi muốn ăn'], ans: 2 },
      { text: "她是我的老师", meaning: "Cô ấy là giáo viên của tôi", opts: ['Cô ấy là bạn tôi', 'Cô ấy là chị tôi', 'Cô ấy là giáo viên của tôi', 'Cô ấy là bác sĩ'], ans: 2 },
      { text: "明天见", meaning: "Hẹn gặp lại ngày mai", opts: ['Tạm biệt', 'Hẹn gặp lại ngày mai', 'Gặp lại sau', 'Hẹn gặp lại hôm nay'], ans: 1 },
    ]
  },

  hsk2: {
    name: "HSK 2",
    level: 2,
    color: "#2980b9",
    gradient: "linear-gradient(135deg, #1a4a7a, #2980b9)",
    description: "300 từ vựng trung cấp sơ",
    vocabulary: [
      { hanzi: "但是", pinyin: "dàn shì", meaning: "nhưng / nhưng mà", example: "我想去，但是我没有时间。", ex_vi: "Tôi muốn đi nhưng tôi không có thời gian.", category: "Liên từ" },
      { hanzi: "因为", pinyin: "yīn wèi", meaning: "vì / bởi vì", example: "因为下雨，我没去。", ex_vi: "Vì trời mưa, tôi không đi.", category: "Liên từ" },
      { hanzi: "所以", pinyin: "suǒ yǐ", meaning: "vì vậy / cho nên", example: "我生病了，所以没来。", ex_vi: "Tôi bị bệnh nên không đến.", category: "Liên từ" },
      { hanzi: "如果", pinyin: "rú guǒ", meaning: "nếu / nếu như", example: "如果你有时间，来找我。", ex_vi: "Nếu bạn có thời gian, hãy đến tìm tôi.", category: "Liên từ" },
      { hanzi: "已经", pinyin: "yǐ jīng", meaning: "đã / đã rồi", example: "我已经吃了。", ex_vi: "Tôi đã ăn rồi.", category: "Trạng từ" },
      { hanzi: "一起", pinyin: "yī qǐ", meaning: "cùng nhau", example: "我们一起去吧！", ex_vi: "Chúng ta cùng đi nhé!", category: "Trạng từ" },
      { hanzi: "还是", pinyin: "hái shì", meaning: "hay là / vẫn là", example: "你喝茶还是喝咖啡？", ex_vi: "Bạn uống trà hay cà phê?", category: "Trạng từ" },
      { hanzi: "就", pinyin: "jiù", meaning: "thì / liền / chỉ", example: "他一回来就睡了。", ex_vi: "Anh ấy vừa về là ngủ ngay.", category: "Trạng từ" },
      { hanzi: "知道", pinyin: "zhī dào", meaning: "biết", example: "我不知道他在哪里。", ex_vi: "Tôi không biết anh ấy ở đâu.", category: "Động từ" },
      { hanzi: "觉得", pinyin: "jué de", meaning: "cảm thấy / cho rằng", example: "我觉得这个好。", ex_vi: "Tôi thấy cái này tốt.", category: "Động từ" },
      { hanzi: "希望", pinyin: "xī wàng", meaning: "hy vọng / mong muốn", example: "我希望你快乐。", ex_vi: "Tôi hy vọng bạn hạnh phúc.", category: "Động từ" },
      { hanzi: "需要", pinyin: "xū yào", meaning: "cần / cần thiết", example: "我需要帮助。", ex_vi: "Tôi cần giúp đỡ.", category: "Động từ" },
      { hanzi: "开始", pinyin: "kāi shǐ", meaning: "bắt đầu", example: "课开始了！", ex_vi: "Lớp học bắt đầu rồi!", category: "Động từ" },
      { hanzi: "告诉", pinyin: "gào su", meaning: "nói cho biết / bảo", example: "请告诉我你的名字。", ex_vi: "Hãy cho tôi biết tên bạn.", category: "Động từ" },
      { hanzi: "帮助", pinyin: "bāng zhù", meaning: "giúp đỡ", example: "谢谢你的帮助！", ex_vi: "Cảm ơn sự giúp đỡ của bạn!", category: "Động từ" },
      { hanzi: "喜欢", pinyin: "xǐ huan", meaning: "thích / yêu thích", example: "我喜欢吃中国菜。", ex_vi: "Tôi thích ăn đồ ăn Trung Quốc.", category: "Động từ" },
      { hanzi: "认识", pinyin: "rèn shi", meaning: "quen biết / nhận ra", example: "认识你很高兴！", ex_vi: "Rất vui được biết bạn!", category: "Động từ" },
      { hanzi: "买", pinyin: "mǎi", meaning: "mua", example: "我去买东西。", ex_vi: "Tôi đi mua đồ.", category: "Động từ" },
      { hanzi: "卖", pinyin: "mài", meaning: "bán", example: "这里卖什么？", ex_vi: "Ở đây bán cái gì?", category: "Động từ" },
      { hanzi: "走", pinyin: "zǒu", meaning: "đi bộ / đi", example: "我们走着去吧。", ex_vi: "Chúng ta đi bộ đến nhé.", category: "Động từ" },
      { hanzi: "时间", pinyin: "shí jiān", meaning: "thời gian", example: "我没有时间。", ex_vi: "Tôi không có thời gian.", category: "Danh từ" },
      { hanzi: "地方", pinyin: "dì fang", meaning: "nơi chốn / địa điểm", example: "这个地方很美。", ex_vi: "Nơi này rất đẹp.", category: "Danh từ" },
      { hanzi: "问题", pinyin: "wèn tí", meaning: "vấn đề / câu hỏi", example: "这个问题很难。", ex_vi: "Vấn đề này rất khó.", category: "Danh từ" },
      { hanzi: "事情", pinyin: "shì qing", meaning: "việc / sự việc", example: "你有什么事情？", ex_vi: "Bạn có việc gì vậy?", category: "Danh từ" },
      { hanzi: "身体", pinyin: "shēn tǐ", meaning: "cơ thể / sức khỏe", example: "你身体好吗？", ex_vi: "Sức khỏe của bạn tốt không?", category: "Danh từ" },
      { hanzi: "天气", pinyin: "tiān qì", meaning: "thời tiết", example: "今天天气不好。", ex_vi: "Hôm nay thời tiết không tốt.", category: "Danh từ" },
      { hanzi: "工作", pinyin: "gōng zuò", meaning: "công việc / làm việc", example: "你的工作怎么样？", ex_vi: "Công việc của bạn thế nào?", category: "Danh từ" },
      { hanzi: "手机", pinyin: "shǒu jī", meaning: "điện thoại di động", example: "我的手机在哪里？", ex_vi: "Điện thoại của tôi ở đâu?", category: "Danh từ" },
      { hanzi: "电脑", pinyin: "diàn nǎo", meaning: "máy tính", example: "我用电脑工作。", ex_vi: "Tôi làm việc bằng máy tính.", category: "Danh từ" },
      { hanzi: "钱", pinyin: "qián", meaning: "tiền", example: "你有多少钱？", ex_vi: "Bạn có bao nhiêu tiền?", category: "Danh từ" },
      { hanzi: "比较", pinyin: "bǐ jiào", meaning: "tương đối / khá", example: "今天比较冷。", ex_vi: "Hôm nay khá lạnh.", category: "Trạng từ" },
      { hanzi: "漂亮", pinyin: "piào liang", meaning: "đẹp / xinh", example: "她很漂亮。", ex_vi: "Cô ấy rất đẹp.", category: "Tính từ" },
      { hanzi: "便宜", pinyin: "pián yi", meaning: "rẻ", example: "这个很便宜。", ex_vi: "Cái này rất rẻ.", category: "Tính từ" },
      { hanzi: "贵", pinyin: "guì", meaning: "đắt", example: "这件衣服太贵了。", ex_vi: "Chiếc áo này quá đắt.", category: "Tính từ" },
      { hanzi: "快", pinyin: "kuài", meaning: "nhanh", example: "请快一点！", ex_vi: "Hãy nhanh lên!", category: "Tính từ" },
      { hanzi: "慢", pinyin: "màn", meaning: "chậm", example: "他走得很慢。", ex_vi: "Anh ấy đi rất chậm.", category: "Tính từ" },
      { hanzi: "早", pinyin: "zǎo", meaning: "sớm / buổi sáng", example: "你起得很早。", ex_vi: "Bạn dậy rất sớm.", category: "Tính từ" },
      { hanzi: "晚", pinyin: "wǎn", meaning: "muộn / buổi tối", example: "今晚我们去看电影。", ex_vi: "Tối nay chúng ta đi xem phim.", category: "Tính từ" },
      { hanzi: "累", pinyin: "lèi", meaning: "mệt", example: "我很累，想睡觉。", ex_vi: "Tôi rất mệt, muốn ngủ.", category: "Tính từ" },
      { hanzi: "饿", pinyin: "è", meaning: "đói", example: "我很饿，我们去吃饭吧。", ex_vi: "Tôi đói lắm, chúng ta đi ăn nhé.", category: "Tính từ" },
    ],
    quiz: [
      { q: '"但是" có nghĩa là gì?', opts: ['Vì vậy', 'Nhưng', 'Nếu', 'Vì'], ans: 1 },
      { q: '"已经" có nghĩa là gì?', opts: ['Vẫn còn', 'Đã rồi', 'Sắp', 'Chưa'], ans: 1 },
      { q: '"知道" có nghĩa là gì?', opts: ['Hiểu', 'Biết', 'Học', 'Nghe'], ans: 1 },
      { q: '"喜欢" có nghĩa là gì?', opts: ['Ghét', 'Muốn', 'Thích', 'Cần'], ans: 2 },
      { q: 'Từ nào có nghĩa là "thời gian"?', opts: ['地方', '问题', '时间', '事情'], ans: 2 },
      { q: '"漂亮" có nghĩa là gì?', opts: ['Xấu', 'Đẹp', 'Cao', 'Nhỏ'], ans: 1 },
      { q: '"便宜" và "贵" là?', opts: ['Nhanh và chậm', 'Rẻ và đắt', 'Sớm và muộn', 'Đói và no'], ans: 1 },
      { q: 'Câu nào đúng nghĩa "Tôi cần giúp đỡ"?', opts: ['我帮助你', '我需要帮助', '我喜欢帮助', '我知道帮助'], ans: 1 },
      { q: '"工作" có thể là gì?', opts: ['Chỉ là danh từ (công việc)', 'Chỉ là động từ (làm việc)', 'Cả danh từ và động từ', 'Tính từ'], ans: 2 },
      { q: '"一起" có nghĩa là gì?', opts: ['Một mình', 'Cùng nhau', 'Ngay lập tức', 'Tất cả'], ans: 1 },
      { q: 'Pinyin của "手机" là?', opts: ['diàn nǎo', 'shǒu jī', 'diàn huà', 'diàn shì'], ans: 1 },
      { q: '"累" có nghĩa là gì?', opts: ['Đói', 'Khát', 'Mệt', 'Buồn'], ans: 2 },
      { q: '"所以" có nghĩa là gì?', opts: ['Nhưng', 'Nếu', 'Vì', 'Vì vậy'], ans: 3 },
      { q: '"觉得" có nghĩa là gì?', opts: ['Biết chắc', 'Cảm thấy/Cho rằng', 'Nghe nói', 'Nhìn thấy'], ans: 1 },
      { q: 'Câu "如果你有时间，来找我" có nghĩa là gì?', opts: ['Khi nào bạn đến tìm tôi', 'Nếu bạn có thời gian, hãy đến tìm tôi', 'Bạn có thời gian không, đến tìm tôi đi', 'Vì bạn có thời gian nên đến tìm tôi'], ans: 1 },
    ],
    fillBlank: [
      { sentence: "我___去，___我没有时间。(muốn - nhưng)", blank: "想...但是", hint: "xiǎng...dàn shì", context: "Tôi ___ đi ___ tôi không có thời gian." },
      { sentence: "你喝茶___喝咖啡？(hay là)", blank: "还是", hint: "hái shì", context: "Bạn uống trà ___ uống cà phê?" },
      { sentence: "我___吃了。(đã)", blank: "已经", hint: "yǐ jīng", context: "Tôi ___ ăn rồi." },
      { sentence: "这件衣服太___了！(đắt)", blank: "贵", hint: "guì", context: "Chiếc áo này quá ___!" },
      { sentence: "我很___，想睡觉。(mệt)", blank: "累", hint: "lèi", context: "Tôi rất ___, muốn ngủ." },
      { sentence: "___你有时间，来找我。(nếu)", blank: "如果", hint: "rú guǒ", context: "___ bạn có thời gian, đến tìm tôi." },
      { sentence: "我___吃中国菜。(thích)", blank: "喜欢", hint: "xǐ huan", context: "Tôi ___ ăn đồ Trung Quốc." },
      { sentence: "我生病了，___没来。(vì vậy)", blank: "所以", hint: "suǒ yǐ", context: "Tôi bị bệnh ___ không đến." },
      { sentence: "我___帮助。(cần)", blank: "需要", hint: "xū yào", context: "Tôi ___ giúp đỡ." },
      { sentence: "我们___去吧！(cùng nhau)", blank: "一起", hint: "yī qǐ", context: "Chúng ta ___ đi nhé!" },
    ],
    listening: [
      { text: "我已经吃了", meaning: "Tôi đã ăn rồi", opts: ['Tôi muốn ăn', 'Tôi đã ăn rồi', 'Tôi chưa ăn', 'Tôi không ăn'], ans: 1 },
      { text: "她很漂亮", meaning: "Cô ấy rất đẹp", opts: ['Cô ấy rất tốt', 'Cô ấy rất vui', 'Cô ấy rất đẹp', 'Cô ấy rất giỏi'], ans: 2 },
      { text: "我需要帮助", meaning: "Tôi cần giúp đỡ", opts: ['Tôi muốn giúp đỡ', 'Tôi cần giúp đỡ', 'Tôi không cần giúp', 'Tôi có thể giúp'], ans: 1 },
      { text: "如果你有时间，来找我", meaning: "Nếu bạn có thời gian, hãy đến tìm tôi", opts: ['Vì bạn có thời gian nên đến tìm tôi', 'Nếu bạn có thời gian, hãy đến tìm tôi', 'Khi bạn có thời gian, tôi sẽ đến', 'Bạn có thời gian không?'], ans: 1 },
      { text: "这件衣服太贵了", meaning: "Chiếc áo này quá đắt", opts: ['Chiếc áo này rất đẹp', 'Chiếc áo này quá rẻ', 'Chiếc áo này quá đắt', 'Tôi muốn mua áo'], ans: 2 },
      { text: "我们一起去吧", meaning: "Chúng ta cùng đi nhé", opts: ['Chúng ta đi một mình', 'Bạn đi trước đi', 'Chúng ta cùng đi nhé', 'Tôi muốn đi'], ans: 2 },
      { text: "因为下雨，我没去", meaning: "Vì trời mưa, tôi không đi", opts: ['Dù trời mưa tôi vẫn đi', 'Vì trời mưa, tôi không đi', 'Trời mưa và tôi đi', 'Tôi muốn đi nhưng trời mưa'], ans: 1 },
      { text: "你喝茶还是喝咖啡", meaning: "Bạn uống trà hay cà phê?", opts: ['Bạn muốn uống gì?', 'Bạn có uống trà không?', 'Bạn uống trà hay cà phê?', 'Bạn thích uống gì?'], ans: 2 },
      { text: "我很累，想睡觉", meaning: "Tôi rất mệt, muốn ngủ", opts: ['Tôi rất vui, muốn đi chơi', 'Tôi rất đói, muốn ăn', 'Tôi rất mệt, muốn ngủ', 'Tôi rất bận, không ngủ được'], ans: 2 },
      { text: "认识你很高兴", meaning: "Rất vui được biết bạn", opts: ['Tôi biết bạn rồi', 'Rất vui được biết bạn', 'Bạn có vui không?', 'Gặp lại bạn thật vui'], ans: 1 },
    ]
  },

  hsk3: {
    name: "HSK 3",
    level: 3,
    color: "#8e44ad",
    gradient: "linear-gradient(135deg, #5b2c6f, #8e44ad)",
    description: "600 từ vựng trung cấp",
    vocabulary: [
      { hanzi: "虽然…但是", pinyin: "suī rán…dàn shì", meaning: "mặc dù…nhưng", example: "虽然很难，但是我会继续努力。", ex_vi: "Mặc dù rất khó nhưng tôi sẽ tiếp tục cố gắng.", category: "Cặp liên từ" },
      { hanzi: "不但…而且", pinyin: "bù dàn…ér qiě", meaning: "không những…mà còn", example: "他不但聪明，而且勤快。", ex_vi: "Anh ấy không những thông minh mà còn chăm chỉ.", category: "Cặp liên từ" },
      { hanzi: "既然", pinyin: "jì rán", meaning: "đã vậy / đã như thế thì", example: "既然你不想去，就不去吧。", ex_vi: "Đã vậy bạn không muốn đi thì thôi vậy.", category: "Liên từ" },
      { hanzi: "于是", pinyin: "yú shì", meaning: "vì vậy / do đó (tường thuật)", example: "他迟到了，于是大家都等他。", ex_vi: "Anh ấy đến muộn, vì vậy mọi người đều chờ anh ấy.", category: "Liên từ" },
      { hanzi: "其实", pinyin: "qí shí", meaning: "thực ra / thật ra", example: "其实我不喜欢这个。", ex_vi: "Thật ra tôi không thích cái này.", category: "Trạng từ" },
      { hanzi: "当然", pinyin: "dāng rán", meaning: "tất nhiên / dĩ nhiên", example: "当然，我会帮你！", ex_vi: "Tất nhiên, tôi sẽ giúp bạn!", category: "Trạng từ" },
      { hanzi: "可能", pinyin: "kě néng", meaning: "có thể / có lẽ", example: "他可能今天不来。", ex_vi: "Có lẽ hôm nay anh ấy không đến.", category: "Trạng từ" },
      { hanzi: "一定", pinyin: "yī dìng", meaning: "nhất định / chắc chắn", example: "你一定要努力！", ex_vi: "Bạn nhất định phải cố gắng!", category: "Trạng từ" },
      { hanzi: "应该", pinyin: "yīng gāi", meaning: "nên / cần phải", example: "你应该多休息。", ex_vi: "Bạn nên nghỉ ngơi nhiều hơn.", category: "Động từ trợ" },
      { hanzi: "必须", pinyin: "bì xū", meaning: "phải / bắt buộc phải", example: "你必须完成作业。", ex_vi: "Bạn bắt buộc phải hoàn thành bài tập.", category: "Động từ trợ" },
      { hanzi: "发现", pinyin: "fā xiàn", meaning: "phát hiện / nhận ra", example: "我发现了一个问题。", ex_vi: "Tôi phát hiện ra một vấn đề.", category: "Động từ" },
      { hanzi: "发展", pinyin: "fā zhǎn", meaning: "phát triển", example: "这个城市发展很快。", ex_vi: "Thành phố này phát triển rất nhanh.", category: "Động từ" },
      { hanzi: "影响", pinyin: "yǐng xiǎng", meaning: "ảnh hưởng", example: "天气影响我们的心情。", ex_vi: "Thời tiết ảnh hưởng đến tâm trạng của chúng ta.", category: "Động từ" },
      { hanzi: "注意", pinyin: "zhù yì", meaning: "chú ý / cẩn thận", example: "请注意安全！", ex_vi: "Hãy chú ý an toàn!", category: "Động từ" },
      { hanzi: "解决", pinyin: "jiě jué", meaning: "giải quyết", example: "我们需要解决这个问题。", ex_vi: "Chúng ta cần giải quyết vấn đề này.", category: "Động từ" },
      { hanzi: "提高", pinyin: "tí gāo", meaning: "nâng cao / cải thiện", example: "怎么提高汉语水平？", ex_vi: "Làm thế nào để nâng cao trình độ tiếng Hán?", category: "Động từ" },
      { hanzi: "改变", pinyin: "gǎi biàn", meaning: "thay đổi", example: "我想改变自己。", ex_vi: "Tôi muốn thay đổi bản thân.", category: "Động từ" },
      { hanzi: "出现", pinyin: "chū xiàn", meaning: "xuất hiện", example: "问题突然出现了。", ex_vi: "Vấn đề bỗng nhiên xuất hiện.", category: "Động từ" },
      { hanzi: "消失", pinyin: "xiāo shī", meaning: "biến mất", example: "他突然消失了。", ex_vi: "Anh ấy đột nhiên biến mất.", category: "Động từ" },
      { hanzi: "努力", pinyin: "nǔ lì", meaning: "cố gắng / chăm chỉ", example: "我会更努力地学习。", ex_vi: "Tôi sẽ học tập chăm chỉ hơn.", category: "Động từ/Tính từ" },
      { hanzi: "成功", pinyin: "chéng gōng", meaning: "thành công", example: "祝你成功！", ex_vi: "Chúc bạn thành công!", category: "Động từ/Danh từ" },
      { hanzi: "失败", pinyin: "shī bài", meaning: "thất bại", example: "失败是成功之母。", ex_vi: "Thất bại là mẹ thành công.", category: "Động từ/Danh từ" },
      { hanzi: "继续", pinyin: "jì xù", meaning: "tiếp tục", example: "请继续！", ex_vi: "Hãy tiếp tục!", category: "Động từ" },
      { hanzi: "完成", pinyin: "wán chéng", meaning: "hoàn thành", example: "你完成作业了吗？", ex_vi: "Bạn đã hoàn thành bài tập chưa?", category: "Động từ" },
      { hanzi: "准备", pinyin: "zhǔn bèi", meaning: "chuẩn bị", example: "我准备考试。", ex_vi: "Tôi chuẩn bị thi.", category: "Động từ" },
      { hanzi: "参加", pinyin: "cān jiā", meaning: "tham gia / tham dự", example: "你参加比赛吗？", ex_vi: "Bạn có tham gia cuộc thi không?", category: "Động từ" },
      { hanzi: "决定", pinyin: "jué dìng", meaning: "quyết định", example: "我已经决定了。", ex_vi: "Tôi đã quyết định rồi.", category: "Động từ" },
      { hanzi: "选择", pinyin: "xuǎn zé", meaning: "lựa chọn", example: "这是你的选择。", ex_vi: "Đây là sự lựa chọn của bạn.", category: "Động từ/Danh từ" },
      { hanzi: "经验", pinyin: "jīng yàn", meaning: "kinh nghiệm", example: "他有丰富的工作经验。", ex_vi: "Anh ấy có kinh nghiệm làm việc phong phú.", category: "Danh từ" },
      { hanzi: "方法", pinyin: "fāng fǎ", meaning: "phương pháp / cách", example: "你有什么好方法？", ex_vi: "Bạn có phương pháp tốt nào không?", category: "Danh từ" },
      { hanzi: "结果", pinyin: "jiē guǒ", meaning: "kết quả", example: "考试结果怎么样？", ex_vi: "Kết quả thi thế nào?", category: "Danh từ" },
      { hanzi: "原因", pinyin: "yuán yīn", meaning: "nguyên nhân / lý do", example: "你知道原因吗？", ex_vi: "Bạn có biết lý do không?", category: "Danh từ" },
      { hanzi: "目的", pinyin: "mù dì", meaning: "mục đích", example: "你的目的是什么？", ex_vi: "Mục đích của bạn là gì?", category: "Danh từ" },
      { hanzi: "机会", pinyin: "jī huì", meaning: "cơ hội", example: "这是一个好机会！", ex_vi: "Đây là một cơ hội tốt!", category: "Danh từ" },
      { hanzi: "条件", pinyin: "tiáo jiàn", meaning: "điều kiện", example: "这里的条件很好。", ex_vi: "Điều kiện ở đây rất tốt.", category: "Danh từ" },
      { hanzi: "环境", pinyin: "huán jìng", meaning: "môi trường / hoàn cảnh", example: "环境很重要。", ex_vi: "Môi trường rất quan trọng.", category: "Danh từ" },
      { hanzi: "社会", pinyin: "shè huì", meaning: "xã hội", example: "现代社会发展很快。", ex_vi: "Xã hội hiện đại phát triển rất nhanh.", category: "Danh từ" },
      { hanzi: "文化", pinyin: "wén huà", meaning: "văn hóa", example: "中国文化很丰富。", ex_vi: "Văn hóa Trung Quốc rất phong phú.", category: "Danh từ" },
      { hanzi: "关系", pinyin: "guān xi", meaning: "quan hệ / mối quan hệ", example: "我们关系很好。", ex_vi: "Mối quan hệ của chúng tôi rất tốt.", category: "Danh từ" },
      { hanzi: "态度", pinyin: "tài du", meaning: "thái độ", example: "你的态度不好。", ex_vi: "Thái độ của bạn không tốt.", category: "Danh từ" },
      { hanzi: "重要", pinyin: "zhòng yào", meaning: "quan trọng", example: "健康最重要。", ex_vi: "Sức khỏe quan trọng nhất.", category: "Tính từ" },
      { hanzi: "聪明", pinyin: "cōng ming", meaning: "thông minh", example: "这个孩子很聪明。", ex_vi: "Đứa trẻ này rất thông minh.", category: "Tính từ" },
      { hanzi: "认真", pinyin: "rèn zhēn", meaning: "nghiêm túc / chăm chú", example: "上课要认真听。", ex_vi: "Lên lớp phải chú ý nghe.", category: "Tính từ" },
      { hanzi: "简单", pinyin: "jiǎn dān", meaning: "đơn giản", example: "这个问题很简单。", ex_vi: "Câu hỏi này rất đơn giản.", category: "Tính từ" },
      { hanzi: "复杂", pinyin: "fù zá", meaning: "phức tạp", example: "这个情况很复杂。", ex_vi: "Tình huống này rất phức tạp.", category: "Tính từ" },
      { hanzi: "特别", pinyin: "tè bié", meaning: "đặc biệt / đặc biệt là", example: "今天特别冷。", ex_vi: "Hôm nay đặc biệt lạnh.", category: "Tính từ/Trạng từ" },
      { hanzi: "突然", pinyin: "tū rán", meaning: "đột nhiên / bất ngờ", example: "他突然出现了。", ex_vi: "Anh ấy đột nhiên xuất hiện.", category: "Trạng từ" },
      { hanzi: "渐渐", pinyin: "jiàn jiàn", meaning: "dần dần", example: "天气渐渐变冷了。", ex_vi: "Thời tiết dần dần trở lạnh.", category: "Trạng từ" },
      { hanzi: "互相", pinyin: "hù xiāng", meaning: "lẫn nhau / cùng nhau", example: "我们互相帮助。", ex_vi: "Chúng ta giúp đỡ lẫn nhau.", category: "Trạng từ" },
      { hanzi: "根据", pinyin: "gēn jù", meaning: "dựa vào / căn cứ vào", example: "根据规定，不能迟到。", ex_vi: "Theo quy định, không được đến muộn.", category: "Giới từ" },
    ],
    quiz: [
      { q: '"虽然…但是" có cấu trúc nghĩa là gì?', opts: ['Không những…mà còn', 'Mặc dù…nhưng', 'Vì…nên', 'Nếu…thì'], ans: 1 },
      { q: '"必须" và "应该" khác nhau như thế nào?', opts: ['"必须" mềm hơn "应该"', '"应该" là bắt buộc, "必须" là nên', '"必须" là bắt buộc, "应该" là nên', 'Hai từ giống nhau'], ans: 2 },
      { q: '"其实" có nghĩa là gì?', opts: ['Tất nhiên', 'Thật ra', 'Có lẽ', 'Nhất định'], ans: 1 },
      { q: '"失败是成功之母" nghĩa là gì?', opts: ['Thành công trước, thất bại sau', 'Thất bại là mẹ thành công', 'Mẹ dạy chúng ta thành công', 'Thành công cần có mẹ'], ans: 1 },
      { q: 'Từ nào có nghĩa là "cơ hội"?', opts: ['条件', '原因', '机会', '结果'], ans: 2 },
      { q: '"提高汉语水平" có nghĩa là gì?', opts: ['Học tiếng Hán', 'Nâng cao trình độ tiếng Hán', 'Thi tiếng Hán', 'Dạy tiếng Hán'], ans: 1 },
      { q: '"突然" có nghĩa là gì?', opts: ['Dần dần', 'Đột nhiên', 'Luôn luôn', 'Thỉnh thoảng'], ans: 1 },
      { q: 'Câu nào dùng "不但…而且" đúng?', opts: ['不但天气好，而且我们出去。', '不但他聪明，而且他勤快。', '不但我去，而且你不去。', '不但很远，而且我走路。'], ans: 1 },
      { q: '"环境" có nghĩa là gì?', opts: ['Điều kiện', 'Môi trường', 'Xã hội', 'Văn hóa'], ans: 1 },
      { q: '"认真" có nghĩa là gì?', opts: ['Thông minh', 'Đơn giản', 'Nghiêm túc/Chăm chú', 'Phức tạp'], ans: 2 },
      { q: '"影响" có nghĩa là gì?', opts: ['Phát triển', 'Phát hiện', 'Ảnh hưởng', 'Biến mất'], ans: 2 },
      { q: 'Điền vào chỗ trống: "你___更努力学习。" (nên)', opts: ['必须', '应该', '一定', '可能'], ans: 1 },
      { q: '"渐渐" có nghĩa là gì?', opts: ['Đột nhiên', 'Dần dần', 'Nhanh chóng', 'Lặp tức'], ans: 1 },
      { q: '"经验" có nghĩa là gì?', opts: ['Phương pháp', 'Kết quả', 'Kinh nghiệm', 'Nguyên nhân'], ans: 2 },
      { q: '"根据规定" có nghĩa là gì?', opts: ['Theo quy định', 'Vì quy định', 'Dù có quy định', 'Nếu có quy định'], ans: 0 },
      { q: 'Câu "他可能今天不来" có nghĩa là gì?', opts: ['Anh ấy chắc chắn không đến hôm nay', 'Có lẽ hôm nay anh ấy không đến', 'Hôm nay anh ấy không đến', 'Anh ấy không muốn đến hôm nay'], ans: 1 },
      { q: '"关系" có nghĩa là gì?', opts: ['Thái độ', 'Tình huống', 'Quan hệ', 'Điều kiện'], ans: 2 },
      { q: '"简单" và "复杂" là?', opts: ['Quan trọng và không quan trọng', 'Đơn giản và phức tạp', 'Đúng và sai', 'Dễ và khó'], ans: 1 },
      { q: 'Pinyin của "选择" là?', opts: ['jué dìng', 'xuǎn zé', 'cān jiā', 'wán chéng'], ans: 1 },
      { q: '"文化" có nghĩa là gì?', opts: ['Xã hội', 'Kinh tế', 'Văn hóa', 'Giáo dục'], ans: 2 },
    ],
    fillBlank: [
      { sentence: "___天气很难，___我会继续努力。(mặc dù - nhưng)", blank: "虽然...但是", hint: "suī rán...dàn shì", context: "___ rất khó ___ tôi sẽ tiếp tục cố gắng." },
      { sentence: "他___聪明，___勤快。(không những - mà còn)", blank: "不但...而且", hint: "bù dàn...ér qiě", context: "Anh ấy ___ thông minh ___ chăm chỉ." },
      { sentence: "你___完成作业了吗？(đã... chưa)", blank: "已经", hint: "yǐ jīng", context: "Bạn ___ hoàn thành bài tập chưa?" },
      { sentence: "你___多休息。(nên)", blank: "应该", hint: "yīng gāi", context: "Bạn ___ nghỉ ngơi nhiều hơn." },
      { sentence: "___，我会帮你！(tất nhiên)", blank: "当然", hint: "dāng rán", context: "___, tôi sẽ giúp bạn!" },
      { sentence: "我___改变自己。(muốn)", blank: "想", hint: "xiǎng", context: "Tôi ___ thay đổi bản thân." },
      { sentence: "这是一个好___！(cơ hội)", blank: "机会", hint: "jī huì", context: "Đây là một ___ tốt!" },
      { sentence: "你必须___作业。(hoàn thành)", blank: "完成", hint: "wán chéng", context: "Bạn bắt buộc phải ___ bài tập." },
      { sentence: "___规定，不能迟到。(theo, dựa vào)", blank: "根据", hint: "gēn jù", context: "___ quy định, không được đến muộn." },
      { sentence: "这个问题很___。(phức tạp)", blank: "复杂", hint: "fù zá", context: "Vấn đề này rất ___." },
      { sentence: "他___出现了。(đột nhiên)", blank: "突然", hint: "tū rán", context: "Anh ấy ___ xuất hiện." },
      { sentence: "天气___变冷了。(dần dần)", blank: "渐渐", hint: "jiàn jiàn", context: "Thời tiết ___ trở lạnh." },
    ],
    listening: [
      { text: "虽然很难，但是我会继续努力", meaning: "Mặc dù rất khó nhưng tôi sẽ tiếp tục cố gắng", opts: ['Vì rất khó nên tôi không cố gắng', 'Nếu khó tôi sẽ cố gắng', 'Mặc dù rất khó nhưng tôi sẽ tiếp tục cố gắng', 'Tuy nhiên tôi đã cố gắng'], ans: 2 },
      { text: "你应该多休息", meaning: "Bạn nên nghỉ ngơi nhiều hơn", opts: ['Bạn muốn nghỉ ngơi không?', 'Bạn nên nghỉ ngơi nhiều hơn', 'Bạn phải nghỉ ngơi ngay', 'Bạn đã nghỉ ngơi chưa?'], ans: 1 },
      { text: "这是一个好机会", meaning: "Đây là một cơ hội tốt", opts: ['Đây là một ý kiến tốt', 'Đây là một phương pháp tốt', 'Đây là một cơ hội tốt', 'Đây là một kết quả tốt'], ans: 2 },
      { text: "他不但聪明，而且勤快", meaning: "Anh ấy không những thông minh mà còn chăm chỉ", opts: ['Anh ấy thông minh nhưng lười biếng', 'Anh ấy không thông minh cũng không chăm chỉ', 'Anh ấy không những thông minh mà còn chăm chỉ', 'Anh ấy thông minh vì chăm chỉ'], ans: 2 },
      { text: "你必须完成作业", meaning: "Bạn bắt buộc phải hoàn thành bài tập", opts: ['Bạn nên hoàn thành bài tập', 'Bạn bắt buộc phải hoàn thành bài tập', 'Bạn có thể hoàn thành bài tập', 'Bạn muốn hoàn thành bài tập'], ans: 1 },
      { text: "失败是成功之母", meaning: "Thất bại là mẹ thành công", opts: ['Mẹ dạy ta thành công', 'Thất bại là mẹ thành công', 'Thành công quan trọng hơn thất bại', 'Đừng sợ thất bại'], ans: 1 },
      { text: "天气渐渐变冷了", meaning: "Thời tiết dần dần trở lạnh", opts: ['Thời tiết đột nhiên trở lạnh', 'Thời tiết dần dần trở lạnh', 'Thời tiết ngày càng nóng hơn', 'Thời tiết hôm nay rất lạnh'], ans: 1 },
      { text: "这个情况很复杂", meaning: "Tình huống này rất phức tạp", opts: ['Tình huống này rất đơn giản', 'Tình huống này rất quan trọng', 'Tình huống này rất phức tạp', 'Tình huống này rất thú vị'], ans: 2 },
      { text: "我发现了一个问题", meaning: "Tôi phát hiện ra một vấn đề", opts: ['Tôi giải quyết một vấn đề', 'Tôi tạo ra một vấn đề', 'Tôi phát hiện ra một vấn đề', 'Tôi biết về vấn đề'], ans: 2 },
      { text: "根据规定，不能迟到", meaning: "Theo quy định, không được đến muộn", opts: ['Vì đến muộn vi phạm quy định', 'Theo quy định, không được đến muộn', 'Nếu đến muộn sẽ bị phạt', 'Quy định không cho phép đến sớm'], ans: 1 },
    ],
    // HSK3 Special: Sentence Arrangement
    arrangement: [
      { words: ["他", "很", "努力", "地", "学习"], answer: "他很努力地学习。", meaning: "Anh ấy học tập rất chăm chỉ." },
      { words: ["虽然", "很忙", "但是", "他", "还是", "来了"], answer: "虽然很忙，但是他还是来了。", meaning: "Mặc dù rất bận nhưng anh ấy vẫn đến." },
      { words: ["根据", "天气预报", "明天", "会", "下雨"], answer: "根据天气预报，明天会下雨。", meaning: "Theo dự báo thời tiết, ngày mai sẽ có mưa." },
      { words: ["他", "不但", "聪明", "而且", "努力"], answer: "他不但聪明，而且努力。", meaning: "Anh ấy không những thông minh mà còn chăm chỉ." },
      { words: ["这", "是", "一个", "好", "机会"], answer: "这是一个好机会。", meaning: "Đây là một cơ hội tốt." },
    ]
  }
};
